version: 0.2
 
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - ls
      - virtualenv env
      - . env/bin/activate
      - python -m pip install --upgrade pip
      - pip install -r requirements/integration_requirements.txt
  build:
    commands:
      - . env/bin/activate
      - python -m pytest src/integration/ --junitxml=pytest_reports/pytest_report.xml
  post_build:
    commands:
      - . env/bin/activate
      - junit2html pytest_reports/pytest_report.xml pytest_reports/pytest_html_report.html
 
reports:
  pytest_reports:
    files:
      - pytest_report.xml
    base-directory: pytest_reports/
    file-format: JUNITXML
 
artifacts:
  files:
    - 'pytest_reports/*'
  name: integration/$CODEBUILD_BUILD_NUMBER